### ISSUE TITLE
test_suites undefined when using MiniTest

### ISSUE THREAD

**Issue by ethagnawl** [qrush/m#45]
This issue looks to be related to #6, but I'm using MiniTest (5.4.2) instead of TestUnit.

```
/home/peter/.rvm/gems/ruby-2.1.2/gems/m-1.3.2/lib/m.rb:231:in `suites': undefined method `test_suites' for Minitest::Unit::TestCase:Class (NoMethodError)
```

**Comment by flooose** [comment]
I have this issue with minitest 5.5.1  and m version 1.3.2. Here are the relevant lines from our Gemfile:

    gem 'minitest'
    gem 'm'

and my ruby: 

    $ ruby --version ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]

**Comment by jaredbeck** [comment]
I can also reproduce this with minitest 5.5.1 and m 1.3.2.  Here's my whole stack trace.

```
/Users/jared/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/m-1.3.2/lib/m.rb:231:in `suites': undefined method `test_suites' for Minitest::Unit::TestCase:Class (NoMethodError)
	from /Users/jared/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/m-1.3.2/lib/m.rb:256:in `tests'
	from /Users/jared/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/m-1.3.2/lib/m.rb:181:in `execute'
	from /Users/jared/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/m-1.3.2/lib/m.rb:121:in `run'
	from /Users/jared/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/m-1.3.2/lib/m.rb:106:in `run'
	from /Users/jared/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/m-1.3.2/bin/m:4:in `<top (required)>'
	from /Users/jared/.rbenv/versions/2.1.2/bin/m:23:in `load'
	from /Users/jared/.rbenv/versions/2.1.2/bin/m:23:in `<main>'
```

**Comment by zamith** [comment]
@ethagnawl Can you test this with version `1.3.3` of `m`? I've added support for Minitest 5, which wasn't there on `1.3.2`.

/cc @flooose @jaredbeck

**Comment by ethagnawl** [comment]
Success! Thanks, @zamith!

**Comment by zamith** [comment]
Cool. :) I'm closing this this issue then.
